query adminReviews($productId: Int, $from: Int, $to: Int, $locale: String, $approved: Boolean, $notapproved: Boolean){
  adminReviews(productId: $productId, from: $from, to: $to, locale: $locale, approved: $approved, notapproved: $notapproved){
    reviewId
    approved
    comment
    locale
    name 
    productId
    score
    id
  }
}