query productReviews($productId: Int!, $approved: Boolean, $locale: String){
  productReviews(productId: $productId, approved: $approved, locale: $locale){
    approved
    comment
    locale
    name
    productId
    score
  }
}